version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
      - '8081:8000'
      - '8081:443'
    volumes:
      - './certs:/certs'