version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
      - '8082:5000'
      - '3000:443'
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app/app.py
    volumes:
      - './certs:/certs'
    command: flask run --host=0.0.0.0 --cert=/certs/server.crt --key=/certs/server.key